// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBga6vpy2rKEdmWaY9jxVRIWrEorGisfPw',
    appId: '1:481372301118:web:63a8e5213fa6bd4ff1ae6f',
    messagingSenderId: '481372301118',
    projectId: 'facebook-clone-flutter-dd41b',
    authDomain: 'facebook-clone-flutter-dd41b.firebaseapp.com',
    storageBucket: 'facebook-clone-flutter-dd41b.firebasestorage.app',
    measurementId: 'G-MYKH6D9Y11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGLzB2NA9pqZ38zxkKE-puu8g6k-0RSqo',
    appId: '1:481372301118:android:e887e8a4635d590af1ae6f',
    messagingSenderId: '481372301118',
    projectId: 'facebook-clone-flutter-dd41b',
    storageBucket: 'facebook-clone-flutter-dd41b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0WeDQU97ZLmVNxXyX3jYeq8__i1EkvL0',
    appId: '1:481372301118:ios:a2429592b1293cf0f1ae6f',
    messagingSenderId: '481372301118',
    projectId: 'facebook-clone-flutter-dd41b',
    storageBucket: 'facebook-clone-flutter-dd41b.firebasestorage.app',
    iosBundleId: 'com.example.facebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0WeDQU97ZLmVNxXyX3jYeq8__i1EkvL0',
    appId: '1:481372301118:ios:a2429592b1293cf0f1ae6f',
    messagingSenderId: '481372301118',
    projectId: 'facebook-clone-flutter-dd41b',
    storageBucket: 'facebook-clone-flutter-dd41b.firebasestorage.app',
    iosBundleId: 'com.example.facebookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBga6vpy2rKEdmWaY9jxVRIWrEorGisfPw',
    appId: '1:481372301118:web:7fd7a03bcaad4aa3f1ae6f',
    messagingSenderId: '481372301118',
    projectId: 'facebook-clone-flutter-dd41b',
    authDomain: 'facebook-clone-flutter-dd41b.firebaseapp.com',
    storageBucket: 'facebook-clone-flutter-dd41b.firebasestorage.app',
    measurementId: 'G-05GTZTML5W',
  );
}
